import { Children, type ReactNode } from 'react'
import {
  AlarmClock, Anchor, Apple, ArrowRight, Award, Ban, Battery, Bed, Beer, Bell,
  Bike, BookOpen, Bookmark, Brain, Brush, Building, Cake, Calculator,
  CalendarDays, Camera, Candy, Car, ChartBar, Check, CircleAlert, CircleCheck, CircleHelp,
  CircleX, Clapperboard, Clock, Cloud, CloudRain, Coffee, Coins, Compass, CreditCard, CupSoda,
  Diamond, Dices, Drama, Droplet, Drumstick, Dumbbell, Ear, Eye, Feather, FileText,
  Film, Flag, Flame, Flower, Folder, Gamepad2, Gem, Ghost, Gift, Glasses, Globe,
  GraduationCap, Headphones, Hourglass, House, IceCreamCone,
  Key, Keyboard, Laptop, Leaf, Library, Lightbulb, Link, Lock, Lollipop, Mail, Map,
  MapPin, Medal, MessageCircle, Mic, Milk, Monitor, Moon, Mountain, Music, NotebookPen,
  Package, Palette, Paperclip, PawPrint, Pen, Pencil, Phone, Pill, Pin, Pizza,
  Plane, Plug, Popcorn, Printer, Puzzle, Rocket, Ruler, Salad, Scissors,
  Search, Send, Settings, Shield, Ship, Shirt, ShoppingCart, Skull, Smartphone,
  Snowflake, Soup, Sparkles, Star, Stethoscope, Sun, Sword, Swords, Tag, Target, Thermometer,
  ThumbsDown, ThumbsUp, Timer, TrainFront, TreePine, TrendingDown, TrendingUp, TriangleAlert,
  Trophy, Truck, Tv, Umbrella, User, Users, Utensils, Wallet, Wand, Watch, Waves, Wifi,
  Wine, Wrench, X, Zap,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, [LucideIcon, string]> = {
  '✅': [CircleCheck, 'text-emerald-500'],
  '✔': [Check, 'text-emerald-600'],
  '❌': [CircleX, 'text-rose-500'],
  '✖': [X, 'text-rose-500'],
  '🚫': [Ban, 'text-rose-500'],
  '⚠': [TriangleAlert, 'text-amber-500'],
  '❗': [CircleAlert, 'text-rose-500'],
  '❓': [CircleHelp, 'text-neutral-500'],
  '💡': [Lightbulb, 'text-amber-500'],
  '📌': [Pin, 'text-brand-600'],
  '⭐': [Star, 'text-amber-400'],
  '🌟': [Sparkles, 'text-amber-400'],
  '✨': [Sparkles, 'text-amber-400'],
  '🔥': [Flame, 'text-orange-500'],
  '🎯': [Target, 'text-brand-600'],
  '➡': [ArrowRight, 'text-neutral-500'],
  '👍': [ThumbsUp, 'text-emerald-600'],
  '👎': [ThumbsDown, 'text-rose-500'],
  '🚀': [Rocket, 'text-brand-600'],
  '🎬': [Clapperboard, 'text-neutral-500'],
  '🎮': [Gamepad2, 'text-brand-600'],
  '🧩': [Puzzle, 'text-brand-600'],
  '🛠': [Wrench, 'text-neutral-500'],
  '🔧': [Wrench, 'text-neutral-500'],
  '⚙': [Settings, 'text-neutral-500'],
  '📈': [TrendingUp, 'text-emerald-500'],
  '📉': [TrendingDown, 'text-rose-500'],
  '📊': [ChartBar, 'text-brand-600'],
  '🎲': [Dices, 'text-brand-600'],
  '🔹': [Diamond, 'text-brand-500'],
  '🔷': [Diamond, 'text-brand-600'],
  '💎': [Gem, 'text-sky-500'],
  '🧠': [Brain, 'text-brand-600'],
  '🎓': [GraduationCap, 'text-brand-600'],
  '📖': [BookOpen, 'text-brand-600'],
  '📚': [Library, 'text-brand-600'],
  '✏': [Pencil, 'text-neutral-500'],
  '📝': [NotebookPen, 'text-neutral-500'],
  '🖊': [Pen, 'text-neutral-500'],
  '💬': [MessageCircle, 'text-brand-600'],
  '✉': [Mail, 'text-neutral-500'],
  '📧': [Mail, 'text-neutral-500'],
  '📤': [Send, 'text-brand-600'],
  '📞': [Phone, 'text-neutral-500'],
  '☎': [Phone, 'text-neutral-500'],
  '🌍': [Globe, 'text-brand-600'],
  '🌎': [Globe, 'text-brand-600'],
  '🌏': [Globe, 'text-brand-600'],
  '🌐': [Globe, 'text-brand-600'],
  '🗺': [Map, 'text-brand-600'],
  '📍': [MapPin, 'text-rose-500'],
  '🧭': [Compass, 'text-brand-600'],
  '✈': [Plane, 'text-brand-600'],
  '🚗': [Car, 'text-neutral-500'],
  '🚲': [Bike, 'text-neutral-500'],
  '🚢': [Ship, 'text-brand-600'],
  '🚆': [TrainFront, 'text-neutral-500'],
  '🏠': [House, 'text-brand-600'],
  '🏡': [House, 'text-brand-600'],
  '🏢': [Building, 'text-neutral-500'],
  '☕': [Coffee, 'text-amber-600'],
  '🍕': [Pizza, 'text-amber-500'],
  '🍎': [Apple, 'text-rose-500'],
  '🎂': [Cake, 'text-pink-400'],
  '🍦': [IceCreamCone, 'text-pink-400'],
  '🍽': [Utensils, 'text-neutral-500'],
  '🥗': [Salad, 'text-emerald-500'],
  '🍲': [Soup, 'text-amber-500'],
  '🍗': [Drumstick, 'text-amber-600'],
  '🍬': [Candy, 'text-pink-400'],
  '🍭': [Lollipop, 'text-pink-400'],
  '🍿': [Popcorn, 'text-amber-500'],
  '🍷': [Wine, 'text-rose-500'],
  '🍺': [Beer, 'text-amber-500'],
  '🥛': [Milk, 'text-neutral-400'],
  '🥤': [CupSoda, 'text-neutral-500'],
  '☀': [Sun, 'text-amber-400'],
  '🌙': [Moon, 'text-indigo-400'],
  '☁': [Cloud, 'text-sky-400'],
  '🌧': [CloudRain, 'text-sky-500'],
  '❄': [Snowflake, 'text-sky-400'],
  '⚡': [Zap, 'text-amber-500'],
  '💧': [Droplet, 'text-sky-500'],
  '🍃': [Leaf, 'text-emerald-500'],
  '🌿': [Leaf, 'text-emerald-600'],
  '🌸': [Flower, 'text-pink-400'],
  '🌷': [Flower, 'text-pink-400'],
  '🌲': [TreePine, 'text-emerald-600'],
  '🌳': [TreePine, 'text-emerald-600'],
  '⛰': [Mountain, 'text-neutral-500'],
  '🌊': [Waves, 'text-sky-500'],
  '👁': [Eye, 'text-neutral-500'],
  '👂': [Ear, 'text-neutral-500'],
  '👤': [User, 'text-neutral-500'],
  '👥': [Users, 'text-neutral-500'],
  '🐾': [PawPrint, 'text-amber-600'],
  '👻': [Ghost, 'text-violet-400'],
  '💀': [Skull, 'text-neutral-500'],
  '⚔': [Swords, 'text-neutral-600'],
  '🗡': [Sword, 'text-neutral-600'],
  '🛡': [Shield, 'text-brand-600'],
  '🪄': [Wand, 'text-violet-500'],
  '🪶': [Feather, 'text-neutral-500'],
  '⏰': [AlarmClock, 'text-neutral-500'],
  '⏳': [Hourglass, 'text-amber-500'],
  '⌛': [Hourglass, 'text-amber-500'],
  '⏱': [Timer, 'text-neutral-500'],
  '🕐': [Clock, 'text-neutral-500'],
  '📅': [CalendarDays, 'text-neutral-500'],
  '🗓': [CalendarDays, 'text-neutral-500'],
  '🔔': [Bell, 'text-amber-500'],
  '🔒': [Lock, 'text-neutral-500'],
  '🔑': [Key, 'text-amber-500'],
  '🔗': [Link, 'text-brand-600'],
  '📎': [Paperclip, 'text-neutral-500'],
  '✂': [Scissors, 'text-neutral-500'],
  '📏': [Ruler, 'text-neutral-500'],
  '🧮': [Calculator, 'text-neutral-500'],
  '💻': [Laptop, 'text-neutral-500'],
  '📱': [Smartphone, 'text-neutral-500'],
  '🖥': [Monitor, 'text-neutral-500'],
  '⌨': [Keyboard, 'text-neutral-500'],
  '🖨': [Printer, 'text-neutral-500'],
  '🔋': [Battery, 'text-emerald-500'],
  '🔌': [Plug, 'text-neutral-500'],
  '📶': [Wifi, 'text-neutral-500'],
  '🔍': [Search, 'text-neutral-500'],
  '🔎': [Search, 'text-neutral-500'],
  '📁': [Folder, 'text-amber-500'],
  '📂': [Folder, 'text-amber-500'],
  '📄': [FileText, 'text-neutral-500'],
  '🔖': [Bookmark, 'text-brand-600'],
  '🏷': [Tag, 'text-brand-600'],
  '🚩': [Flag, 'text-rose-500'],
  '💵': [Coins, 'text-emerald-600'],
  '💰': [Coins, 'text-amber-500'],
  '👛': [Wallet, 'text-amber-600'],
  '💳': [CreditCard, 'text-neutral-500'],
  '🛒': [ShoppingCart, 'text-brand-600'],
  '📦': [Package, 'text-amber-600'],
  '🚚': [Truck, 'text-neutral-500'],
  '☂': [Umbrella, 'text-sky-500'],
  '☔': [Umbrella, 'text-sky-500'],
  '👓': [Glasses, 'text-neutral-500'],
  '👕': [Shirt, 'text-brand-600'],
  '⌚': [Watch, 'text-neutral-500'],
  '🛏': [Bed, 'text-neutral-500'],
  '💊': [Pill, 'text-rose-400'],
  '🌡': [Thermometer, 'text-rose-500'],
  '🩺': [Stethoscope, 'text-brand-600'],
  '🏋': [Dumbbell, 'text-neutral-600'],
  '🏆': [Trophy, 'text-amber-500'],
  '🥇': [Medal, 'text-amber-500'],
  '🎖': [Award, 'text-amber-500'],
  '🎁': [Gift, 'text-rose-500'],
  '🎵': [Music, 'text-brand-600'],
  '🎶': [Music, 'text-brand-600'],
  '🎤': [Mic, 'text-rose-500'],
  '🎧': [Headphones, 'text-brand-600'],
  '📷': [Camera, 'text-neutral-500'],
  '📸': [Camera, 'text-neutral-500'],
  '🎞': [Film, 'text-neutral-500'],
  '📺': [Tv, 'text-neutral-500'],
  '🎨': [Palette, 'text-pink-400'],
  '🖌': [Brush, 'text-neutral-500'],
  '🎭': [Drama, 'text-violet-500'],
  '⚓': [Anchor, 'text-brand-600'],
}

const SPLIT_RE = new RegExp(`(${Object.keys(ICONS).join('|')})\uFE0F?`)

// Replaces known emojis in string children with matching lucide icons.
export function iconify(children: ReactNode): ReactNode {
  return Children.map(children, (c) => {
    if (typeof c !== 'string') return c
    return c.split(SPLIT_RE).map((part, i) => {
      const hit = ICONS[part]
      if (!hit) return part
      const [Icon, cls] = hit
      return <Icon key={i} aria-label={part} className={`inline-block h-[1.45em] w-[1.45em] align-[-0.33em] ${cls}`} />
    })
  })
}
