// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, email, created_at, updated_at, first_name, last_name, status, picture_url, english_level, about_me, native_language, show_translations, speech_strictness)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateAccountParams struct {
	ID               pgtype.UUID
	Email            string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	FirstName        string
	LastName         string
	Status           string
	PictureUrl       string
	EnglishLevel     string
	AboutMe          string
	NativeLanguage   string
	ShowTranslations bool
	SpeechStrictness float64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.PictureUrl,
		arg.EnglishLevel,
		arg.AboutMe,
		arg.NativeLanguage,
		arg.ShowTranslations,
		arg.SpeechStrictness,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsAccountEmail = `-- name: ExistsAccountEmail :one
SELECT EXISTS (
    SELECT 1 FROM accounts WHERE lower(email) = lower($1)
) AS exists
`

func (q *Queries) ExistsAccountEmail(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, existsAccountEmail, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, created_at, updated_at, first_name, last_name, status, picture_url, english_level, about_me, native_language, show_translations, speech_strictness
FROM accounts
WHERE lower(email) = lower($1)
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.PictureUrl,
		&i.EnglishLevel,
		&i.AboutMe,
		&i.NativeLanguage,
		&i.ShowTranslations,
		&i.SpeechStrictness,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, created_at, updated_at, first_name, last_name, status, picture_url, english_level, about_me, native_language, show_translations, speech_strictness
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.PictureUrl,
		&i.EnglishLevel,
		&i.AboutMe,
		&i.NativeLanguage,
		&i.ShowTranslations,
		&i.SpeechStrictness,
	)
	return i, err
}

const getAccountsByIDs = `-- name: GetAccountsByIDs :many
SELECT id, email, created_at, updated_at, first_name, last_name, status, picture_url, english_level, about_me, native_language, show_translations, speech_strictness
FROM accounts
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetAccountsByIDs(ctx context.Context, ids []pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.PictureUrl,
			&i.EnglishLevel,
			&i.AboutMe,
			&i.NativeLanguage,
			&i.ShowTranslations,
			&i.SpeechStrictness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccountsByEmail = `-- name: SearchAccountsByEmail :many
SELECT id, email, created_at, updated_at, first_name, last_name, status, picture_url, english_level, about_me, native_language, show_translations, speech_strictness
FROM accounts
WHERE email ILIKE $1
ORDER BY email ASC
LIMIT $2
`

type SearchAccountsByEmailParams struct {
	Query string
	Lim   int32
}

func (q *Queries) SearchAccountsByEmail(ctx context.Context, arg SearchAccountsByEmailParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccountsByEmail, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.PictureUrl,
			&i.EnglishLevel,
			&i.AboutMe,
			&i.NativeLanguage,
			&i.ShowTranslations,
			&i.SpeechStrictness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :execrows
UPDATE accounts
SET email             = $2,
    updated_at        = $3,
    first_name        = $4,
    last_name         = $5,
    status            = $6,
    english_level     = $7,
    about_me          = $8,
    native_language   = $9,
    show_translations = $10,
    speech_strictness = $11
WHERE id = $1
`

type UpdateAccountParams struct {
	ID               pgtype.UUID
	Email            string
	UpdatedAt        pgtype.Timestamptz
	FirstName        string
	LastName         string
	Status           string
	EnglishLevel     string
	AboutMe          string
	NativeLanguage   string
	ShowTranslations bool
	SpeechStrictness float64
}

// Basic profile update: picture_url is NOT changed here — only via UpdateAccountPicture.
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccount,
		arg.ID,
		arg.Email,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.EnglishLevel,
		arg.AboutMe,
		arg.NativeLanguage,
		arg.ShowTranslations,
		arg.SpeechStrictness,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountPicture = `-- name: UpdateAccountPicture :one
WITH prev AS (
    SELECT picture_url AS old_picture_url
    FROM accounts
    WHERE id = $1
)
UPDATE accounts
SET picture_url = $2,
    updated_at  = $3
FROM prev
WHERE accounts.id = $1
RETURNING prev.old_picture_url AS previous_picture_url
`

type UpdateAccountPictureParams struct {
	ID         pgtype.UUID
	PictureUrl string
	UpdatedAt  pgtype.Timestamptz
}

// Atomically updates picture_url and returns the previous value for deleting the old file.
func (q *Queries) UpdateAccountPicture(ctx context.Context, arg UpdateAccountPictureParams) (string, error) {
	row := q.db.QueryRow(ctx, updateAccountPicture, arg.ID, arg.PictureUrl, arg.UpdatedAt)
	var previous_picture_url string
	err := row.Scan(&previous_picture_url)
	return previous_picture_url, err
}
