// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountRoleByAccount = `-- name: GetAccountRoleByAccount :one
SELECT account_id, role, entity_id
FROM v_account_role
WHERE account_id = $1
`

func (q *Queries) GetAccountRoleByAccount(ctx context.Context, accountID pgtype.UUID) (VAccountRole, error) {
	row := q.db.QueryRow(ctx, getAccountRoleByAccount, accountID)
	var i VAccountRole
	err := row.Scan(&i.AccountID, &i.Role, &i.EntityID)
	return i, err
}
