// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: administrators.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdministrators = `-- name: CountAdministrators :one
SELECT COUNT(*) FROM administrators WHERE deleted_at IS NULL
`

func (q *Queries) CountAdministrators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdministrators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdministrator = `-- name: CreateAdministrator :exec
INSERT INTO administrators (id, account_id, created_at, updated_at)
VALUES ($1, $2, $3, $4)
`

type CreateAdministratorParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) error {
	_, err := q.db.Exec(ctx, createAdministrator,
		arg.ID,
		arg.AccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAdministrator = `-- name: DeleteAdministrator :execrows
UPDATE administrators
SET deleted_at = $2,
    updated_at = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type DeleteAdministratorParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

// Soft-delete: the row remains but is hidden from all Read queries.
func (q *Queries) DeleteAdministrator(ctx context.Context, arg DeleteAdministratorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdministrator, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdministratorByAccountID = `-- name: GetAdministratorByAccountID :one
SELECT id, account_id, created_at, updated_at, deleted_at FROM administrators
WHERE account_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAdministratorByAccountID(ctx context.Context, accountID pgtype.UUID) (Administrator, error) {
	row := q.db.QueryRow(ctx, getAdministratorByAccountID, accountID)
	var i Administrator
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdministratorByID = `-- name: GetAdministratorByID :one
SELECT id, account_id, created_at, updated_at, deleted_at FROM administrators
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAdministratorByID(ctx context.Context, id pgtype.UUID) (Administrator, error) {
	row := q.db.QueryRow(ctx, getAdministratorByID, id)
	var i Administrator
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdministrators = `-- name: ListAdministrators :many
SELECT id, account_id, created_at, updated_at, deleted_at FROM administrators
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdministratorsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAdministrators(ctx context.Context, arg ListAdministratorsParams) ([]Administrator, error) {
	rows, err := q.db.Query(ctx, listAdministrators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Administrator{}
	for rows.Next() {
		var i Administrator
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdministrator = `-- name: UpdateAdministrator :execrows
UPDATE administrators
SET updated_at = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateAdministratorParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateAdministrator(ctx context.Context, arg UpdateAdministratorParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAdministrator, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
