// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCredentialsByAccountID = `-- name: GetCredentialsByAccountID :one
SELECT account_id, password_hash, updated_at
FROM credentials
WHERE account_id = $1
`

func (q *Queries) GetCredentialsByAccountID(ctx context.Context, accountID pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialsByAccountID, accountID)
	var i Credential
	err := row.Scan(&i.AccountID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const upsertCredentials = `-- name: UpsertCredentials :exec
INSERT INTO credentials (account_id, password_hash, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    updated_at    = EXCLUDED.updated_at
`

type UpsertCredentialsParams struct {
	AccountID    pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCredentials(ctx context.Context, arg UpsertCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertCredentials, arg.AccountID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
