// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Email        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	FirstName    string
	LastName     string
	Status       string
	PictureUrl   string
	EnglishLevel string
	AboutMe      string
}

type Administrator struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type AiMessage struct {
	ID               pgtype.UUID
	SessionID        pgtype.UUID
	Role             string
	Content          string
	ToolCalls        []byte
	ToolCallID       string
	ToolName         string
	Model            string
	FinishReason     string
	ReasoningContent string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	CreatedAt        pgtype.Timestamptz
}

type AiSession struct {
	ID               pgtype.UUID
	AccountID        pgtype.UUID
	Model            string
	ContextStartedAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Book struct {
	Slug      string
	Title     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BookChapter struct {
	ID        pgtype.UUID
	Book      string
	Number    int32
	Title     string
	Page      int32
	Words     []byte
	Footer    string
	Theory    string
	Exercises string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Status    string
	Error     string
}

type Credential struct {
	AccountID    pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

type Event struct {
	ID            pgtype.UUID
	RawEventID    pgtype.UUID
	UserID        pgtype.UUID
	Type          string
	Action        string
	Lemma         string
	Pos           string
	GrammarKey    string
	Outcome       string
	Error         []byte
	Context       string
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	WordID        pgtype.UUID
	GrammarRuleID pgtype.UUID
	ClientID      string
	Source        []byte
	Meta          []byte
}

type Film struct {
	ID            pgtype.UUID
	Title         string
	PosterPath    string
	DurationMs    int32
	Status        string
	Error         string
	AudioVariants []byte
	Subtitles     []byte
	CreatedAt     pgtype.Timestamptz
	Description   string
}

type GrammarRule struct {
	ID        pgtype.UUID
	Key       string
	ParentKey string
	Title     string
	CefrLevel string
	Enriched  bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PracticeProgress struct {
	AccountID  pgtype.UUID
	Kind       string
	Number     int32
	VariantKey string
	Answers    []byte
	Completed  bool
	UpdatedAt  pgtype.Timestamptz
}

type PracticeVariant struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Kind      string
	Number    int32
	Title     string
	Exercises string
	CreatedAt pgtype.Timestamptz
	Status    string
	Error     string
}

type QuestMission struct {
	ID        pgtype.UUID
	UserID    string
	Status    string
	Error     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type QuestProfile struct {
	UserID    string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RawEvent struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Status      string
	Version     int32
	Type        string
	Text        string
	Context     string
	Note        string
	Source      []byte
	Meta        []byte
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Error       string
	Session     string
	ClientID    string
}

type VAccountRole struct {
	AccountID pgtype.UUID
	Role      string
	EntityID  pgtype.UUID
}

type Word struct {
	ID        pgtype.UUID
	Key       string
	Lemma     string
	Pos       string
	Type      string
	Enriched  bool
	IsStop    bool
	Cefr      string
	Frequency *float64
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
