// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID               pgtype.UUID
	Email            string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	FirstName        string
	LastName         string
	Status           string
	PictureUrl       string
	EnglishLevel     string
	AboutMe          string
	NativeLanguage   string
	ShowTranslations bool
	SpeechStrictness float64
}

type Administrator struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type AiMessage struct {
	ID               pgtype.UUID
	SessionID        pgtype.UUID
	Role             string
	Content          string
	ToolCalls        []byte
	ToolCallID       string
	ToolName         string
	Model            string
	FinishReason     string
	ReasoningContent string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	CreatedAt        pgtype.Timestamptz
}

type AiProvider struct {
	Feature   string
	BaseUrl   string
	ApiKey    string
	Model     string
	UpdatedAt pgtype.Timestamptz
}

type AiSession struct {
	ID               pgtype.UUID
	AccountID        pgtype.UUID
	Model            string
	ContextStartedAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type BaseForm struct {
	Text     string
	Pos      *string
	IsStop   bool
	Language string
	Meaning  *string
}

type Book struct {
	Slug        string
	Title       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Series      string
	Level       string
	Description string
}

type BookChapter struct {
	ID        pgtype.UUID
	Book      string
	Number    int32
	Title     string
	Page      int32
	Words     []byte
	Footer    string
	Theory    string
	Exercises string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Status    string
	Error     string
}

type Credential struct {
	AccountID    pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

type Event struct {
	ID            pgtype.UUID
	RawEventID    pgtype.UUID
	UserID        pgtype.UUID
	Type          string
	Action        string
	Lemma         string
	Pos           string
	GrammarKey    string
	Outcome       string
	Error         []byte
	Context       string
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	WordID        pgtype.UUID
	GrammarRuleID pgtype.UUID
	ClientID      string
	Source        []byte
	Meta          []byte
}

type Film struct {
	ID            pgtype.UUID
	Title         string
	PosterPath    string
	DurationMs    int32
	Status        string
	Error         string
	AudioVariants []byte
	Subtitles     []byte
	CreatedAt     pgtype.Timestamptz
	Description   string
	Kind          string
	SeriesTitle   string
	Season        int32
	Episode       int32
}

type FilmProgress struct {
	OwnerID    pgtype.UUID
	FilmID     pgtype.UUID
	PositionMs int32
	UpdatedAt  pgtype.Timestamptz
}

type FilmSeries struct {
	Title       string
	Description string
	PosterPath  string
}

type GrammarRule struct {
	ID        pgtype.UUID
	Key       string
	ParentKey string
	Title     string
	CefrLevel string
	Enriched  bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MediaSegment struct {
	ID         pgtype.UUID
	MediaID    pgtype.UUID
	Kind       string
	SegmentIdx int32
	StartPos   int32
	EndPos     int32
	Text       string
	Metadata   []byte
}

type PlatformFlag struct {
	Key       string
	Enabled   bool
	UpdatedAt pgtype.Timestamptz
}

type PracticeProgress struct {
	AccountID  pgtype.UUID
	Kind       string
	Number     int32
	VariantKey string
	Answers    []byte
	Completed  bool
	UpdatedAt  pgtype.Timestamptz
}

type PracticeVariant struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Kind      string
	Number    int32
	Title     string
	Exercises string
	CreatedAt pgtype.Timestamptz
	Status    string
	Error     string
}

type QuestMission struct {
	ID        pgtype.UUID
	UserID    string
	Status    string
	Error     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AuthorID  string
}

type QuestProfile struct {
	UserID    string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RawEvent struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Status      string
	Text        string
	Context     string
	Source      []byte
	Meta        []byte
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Error       string
	ClientID    string
	Skill       string
	Target      string
	Outcome     string
	ClaimedAt   pgtype.Timestamptz
}

type ReaderBook struct {
	ID          pgtype.UUID
	OwnerID     string
	Title       string
	Author      string
	ContentPath string
	TextLength  int32
	Status      string
	Error       string
	CreatedAt   pgtype.Timestamptz
	Description string
	CoverPath   string
	Kind        string
	GroupTitle  string
}

type ReaderCollection struct {
	Title       string
	Description string
	CoverPath   string
}

type ReaderProgress struct {
	OwnerID  string
	BookID   pgtype.UUID
	Position int32
}

type Unit struct {
	ID           pgtype.UUID
	MediaID      pgtype.UUID
	SegmentID    pgtype.UUID
	UnitType     string
	BaseForm     string
	Pos          *string
	SentenceIdx  int32
	UnitMetadata []byte
	Language     string
}

type UnitSpan struct {
	ID       pgtype.UUID
	UnitID   pgtype.UUID
	Position int32
	SpanType string
	Start    int32
	End      int32
	Text     string
}

type VAccountRole struct {
	AccountID pgtype.UUID
	Role      string
	EntityID  pgtype.UUID
}

type VocabUnit struct {
	ID             pgtype.UUID
	AccountID      string
	Text           string
	Kind           string
	Transcription  string
	Translation    string
	Definition     string
	Example        string
	Status         string
	CreatedAt      pgtype.Timestamptz
	Frequency      int32
	Cefr           string
	CorrectStreak  int32
	LastAnsweredAt pgtype.Timestamptz
}

type Word struct {
	ID        pgtype.UUID
	Key       string
	Lemma     string
	Pos       string
	Type      string
	Enriched  bool
	IsStop    bool
	Cefr      string
	Frequency *float64
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
