// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAdministrators(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) error
	DeleteAccount(ctx context.Context, id pgtype.UUID) (int64, error)
	// Soft-delete: the row remains but is hidden from all Read queries.
	DeleteAdministrator(ctx context.Context, arg DeleteAdministratorParams) (int64, error)
	ExistsAccountEmail(ctx context.Context, lower string) (bool, error)
	GetAccountByEmail(ctx context.Context, lower string) (Account, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountRoleByAccount(ctx context.Context, accountID pgtype.UUID) (VAccountRole, error)
	GetAccountsByIDs(ctx context.Context, ids []pgtype.UUID) ([]Account, error)
	GetAdministratorByAccountID(ctx context.Context, accountID pgtype.UUID) (Administrator, error)
	GetAdministratorByID(ctx context.Context, id pgtype.UUID) (Administrator, error)
	GetCredentialsByAccountID(ctx context.Context, accountID pgtype.UUID) (Credential, error)
	ListAdministrators(ctx context.Context, arg ListAdministratorsParams) ([]Administrator, error)
	SearchAccountsByEmail(ctx context.Context, arg SearchAccountsByEmailParams) ([]Account, error)
	// Basic profile update: picture_url is NOT changed here — only via UpdateAccountPicture.
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error)
	// Atomically updates picture_url and returns the previous value for deleting the old file.
	UpdateAccountPicture(ctx context.Context, arg UpdateAccountPictureParams) (string, error)
	UpdateAdministrator(ctx context.Context, arg UpdateAdministratorParams) (int64, error)
	UpsertCredentials(ctx context.Context, arg UpsertCredentialsParams) error
}

var _ Querier = (*Queries)(nil)
