package apps

var Catalog = []App{
	{
		ID:          "profile",
		Name:        "Profile",
		URI:         "/v1/profile",
		Description: "Personal account and settings",
		Group:       "personal",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "chat",
		Name:        "Assistant",
		URI:         "/v1/chat",
		Description: "AI assistant chat",
		Group:       "personal",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "journal",
		Name:        "Events Log",
		URI:         "/v1/journal",
		Description: "System events log: events, errors, and catalog",
		Group:       "admin",
		Disabled:    false,
		Access:      AccessPolicy{AllowRoles: []string{"admin"}},
	},
	{
		ID:          "quest",
		Name:        "Quests",
		URI:         "/v1/quest",
		Description: "Interactive missions for language practice",
		Group:       "practice",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "grammarbook",
		Name:        "Grammarbook",
		URI:         "/v1/grammarbook",
		Description: "Interactive book: Grammar in Use, rules and practice",
		Group:       "books",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "wordbook",
		Name:        "Wordbook",
		URI:         "/v1/wordbook",
		Description: "Interactive book: Vocabulary in Use, words in context",
		Group:       "books",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "phrasebook",
		Name:        "Phrasebook",
		URI:         "/v1/phrasebook",
		Description: "Interactive book: Collocations in Use, natural word combinations",
		Group:       "books",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "essentialbook",
		Name:        "Essentialbook",
		URI:         "/v1/essentialbook",
		Description: "Interactive book: 504 Absolutely Essential Words",
		Group:       "books",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "diary",
		Name:        "Diary",
		URI:         "/v1/diary",
		Description: "Daily English diary with a friendly AI reader and gentle corrections",
		Group:       "practice",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "speaking",
		Name:        "Speaking",
		URI:         "/v1/speaking",
		Description: "Read aloud and get phoneme-level pronunciation feedback",
		Group:       "practice",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "vocab",
		Name:        "My Vocabulary",
		URI:         "/v1/vocab",
		Description: "Personal word collection: add, describe and memorize",
		Group:       "practice",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "reader",
		Name:        "Reader",
		URI:         "/v1/reader",
		Description: "Upload and read books with saved position",
		Group:       "media",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "films",
		Name:        "Films",
		URI:         "/v1/films",
		Description: "Watch films with subtitles",
		Group:       "media",
		Disabled:    false,
		Access:      AccessPolicy{AllowAll: true},
	},
	{
		ID:          "admin",
		Name:        "Accounts",
		URI:         "/v1/admin",
		Description: "Manage accounts and administrators",
		Group:       "admin",
		Disabled:    false,
		Access:      AccessPolicy{AllowRoles: []string{"admin"}},
	},
	{
		ID:          "settings",
		Name:        "Settings",
		URI:         "/v1/settings",
		Description: "Platform configuration: AI providers and models",
		Group:       "admin",
		Disabled:    false,
		Access:      AccessPolicy{AllowRoles: []string{"admin"}},
	},
}
