import openapiTS, { astToString } from 'openapi-typescript'
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import YAML from 'yaml'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OPENAPI_DIR = path.resolve(__dirname, '../../../backend/docs/openapi')
const OUT_DIR = path.resolve(__dirname, 'src/generated')

const STRIPPED_HEADERS = new Set(['authorization'])

const KEEP_PATH = /^\/api\/v\d+\//

async function main() {
  await mkdir(OUT_DIR, { recursive: true })

  const entries = await readdir(OPENAPI_DIR, { withFileTypes: true })
  const yamls = entries
    .filter((e) => e.isFile() && e.name.endsWith('.yaml'))
    .map((e) => e.name)
    .sort()

  if (yamls.length === 0) {
    console.warn(`[codegen] no *.yaml files in ${OPENAPI_DIR}`)
    return
  }

  const modules = []
  const operationsByModule = {}
  for (const yaml of yamls) {
    const moduleName = path.basename(yaml, '.yaml')
    const inputPath = path.join(OPENAPI_DIR, yaml)
    const outputPath = path.join(OUT_DIR, `${moduleName}.ts`)

    const raw = await readFile(inputPath, 'utf8')
    const spec = YAML.parse(raw)
    stripNonApiPaths(spec)
    stripInfraHeaders(spec)
    operationsByModule[moduleName] = collectOperations(spec)

    const ast = await openapiTS(spec, { rootTypes: true })
    const body = astToString(ast)
    await writeFile(outputPath, body, 'utf8')
    modules.push(moduleName)
    console.log(`  ✓ ${moduleName}.ts`)
  }

  const indexLines = [
    ...modules.map(
      (m) =>
        `export type { paths as ${pascal(m)}Paths, components as ${pascal(m)}Components } from './${m}.ts'`,
    ),
    '',
  ]
  await writeFile(path.join(OUT_DIR, 'index.ts'), indexLines.join('\n'), 'utf8')
  console.log(`  ✓ index.ts (${modules.length} module${modules.length === 1 ? '' : 's'})`)

  await writeFile(path.join(OUT_DIR, 'clients.ts'), buildClientsFile(modules), 'utf8')
  console.log(`  ✓ clients.ts`)

  await writeFile(
    path.join(OUT_DIR, 'operations.ts'),
    buildOperationsFile(modules, operationsByModule),
    'utf8',
  )
  const total = Object.values(operationsByModule).reduce((n, arr) => n + arr.length, 0)
  console.log(`  ✓ operations.ts (${total} operation${total === 1 ? '' : 's'})`)
}

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete']

function collectOperations(spec) {
  const out = []
  const paths = spec?.paths
  if (!paths || typeof paths !== 'object') return out
  for (const [urlPath, pathItem] of Object.entries(paths)) {
    if (!pathItem || typeof pathItem !== 'object') continue
    const inheritedParams = Array.isArray(pathItem.parameters) ? pathItem.parameters : []
    for (const method of HTTP_METHODS) {
      const op = pathItem[method]
      if (!op || typeof op !== 'object') continue
      const operationId = typeof op.operationId === 'string' ? op.operationId : null
      if (!operationId) continue
      const opParams = Array.isArray(op.parameters) ? op.parameters : []
      const allParams = [...inheritedParams, ...opParams]
      const hasRequiredParam = allParams.some(
        (p) => p && typeof p === 'object' && (p.in === 'path' || p.in === 'query') && p.required,
      )
      const hasRequiredBody =
        !!op.requestBody &&
        op.requestBody.required !== false &&
        !!(op.requestBody.content && Object.keys(op.requestBody.content).length > 0)
      out.push({
        operationId,
        path: urlPath,
        method,
        requiresInit: hasRequiredParam || hasRequiredBody,
      })
    }
  }
  return out
}

function buildOperationsFile(modules, operationsByModule) {
  const importList = modules.map((m) => `${pascal(m)}Paths`).join(',\n  ')

  const serviceBlocks = modules.map((module) => {
    const ops = operationsByModule[module] ?? []
    if (ops.length === 0) return `    ${module}: {},`
    const ids = new Set()
    const lines = ops
      .filter((op) => {
        if (ids.has(op.operationId)) return false
        ids.add(op.operationId)
        return true
      })
      .map((op) => {
        const fn = op.method.toUpperCase()
        const initType = `MaybeOptionalInit<${pascal(module)}Paths['${op.path}'], '${op.method}'>`
        const initParam = op.requiresInit ? `init: ${initType}` : `init?: ${initType}`
        return `      ${op.operationId}: (${initParam}) => unwrap(clients.${module}.${fn}('${op.path}', init)),`
      })
    return `    ${module}: {\n${lines.join('\n')}\n    },`
  })

  return `// AUTO-GENERATED by codegen.mjs — do not edit.
import type { MaybeOptionalInit } from 'openapi-fetch'
import { unwrap } from '../unwrap.ts'
import { createApiClient, type ApiClientOptions } from './clients.ts'
import type {
  ${importList},
} from './index.ts'

export function createApi(options: ApiClientOptions) {
  const clients = createApiClient(options)
  return {
${serviceBlocks.join('\n')}
  }
}

export type Api = ReturnType<typeof createApi>
`
}

function buildClientsFile(modules) {
  const importList = modules.map((m) => `${pascal(m)}Paths`).join(',\n  ')
  const clientFields = modules.map((m) => `  ${m}: Client<${pascal(m)}Paths>`).join('\n')
  const factoryEntries = modules.map((m) => `    ${m}: make<${pascal(m)}Paths>(),`).join('\n')

  return `// AUTO-GENERATED by codegen.mjs — do not edit.
import createClient, { type Client, type Middleware } from 'openapi-fetch'
import type {
  ${importList},
} from './index.ts'

export interface ApiClientOptions {
  baseUrl: string
  getToken?: () => string | null | undefined
  middleware?: Middleware[]
}

export interface ApiClient {
${clientFields}
}

export function createApiClient(options: ApiClientOptions): ApiClient {
  const { baseUrl, getToken, middleware = [] } = options

  const authInterceptor: Middleware = {
    async onRequest({ request }) {
      const token = getToken?.()
      if (token) request.headers.set('Authorization', \`Bearer \${token}\`)
      return request
    },
  }

  const make = <P extends {}>() => {
    const c = createClient<P>({ baseUrl })
    c.use(authInterceptor, ...middleware)
    return c
  }

  return {
${factoryEntries}
  }
}
`
}

function stripNonApiPaths(spec) {
  const paths = spec?.paths
  if (!paths || typeof paths !== 'object') return
  for (const key of Object.keys(paths)) {
    if (!KEEP_PATH.test(key)) delete paths[key]
  }
}

function stripInfraHeaders(spec) {
  const paths = spec?.paths
  if (!paths || typeof paths !== 'object') return
  for (const pathItem of Object.values(paths)) {
    if (!pathItem || typeof pathItem !== 'object') continue
    for (const op of Object.values(pathItem)) {
      if (!op || typeof op !== 'object') continue
      if (!Array.isArray(op.parameters)) continue
      op.parameters = op.parameters.filter((p) => {
        if (!p || typeof p !== 'object') return true
        if (p.in !== 'header') return true
        return !STRIPPED_HEADERS.has(String(p.name ?? '').toLowerCase())
      })
    }
  }
}

function pascal(s) {
  return s
    .split(/[-_]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

main().catch((err) => {
  console.error('[codegen] failed:', err)
  process.exit(1)
})
